services:
  app:
    image: nikeshhh/phpapp-intuji
    container_name: php-app
    ports:
      - "8000:80"
    networks:
      network:
        ipv4_address: 10.0.0.2

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
          
